/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tubes.perpus;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author Unknown
 */
public class formBook extends javax.swing.JFrame {

    /**
     * Creates new form bukuForm
     */
    public formBook() {
        initComponents();
        viewComboBox();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        mainMenuEmployee mm = new mainMenuEmployee();
        if (mm.edit) {
            btnUpdate.setVisible(true);
            btnAdd.setVisible(false);
            this.setTitle("Edit Data Buku");
        } else {
            btnUpdate.setVisible(false);
            btnAdd.setVisible(true);
            this.setTitle("Tambah Data Buku");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        labelPublisher = new javax.swing.JLabel();
        comboPublisher = new javax.swing.JComboBox<>();
        labelAuthor = new javax.swing.JLabel();
        txtAuthor = new javax.swing.JTextField();
        labelYear = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        labelCategory = new javax.swing.JLabel();
        comboCategory = new javax.swing.JComboBox<>();
        labelQty = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(74, 209, 161));

        labelTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setText("Judul Buku");

        labelPublisher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPublisher.setForeground(new java.awt.Color(255, 255, 255));
        labelPublisher.setText("Penerbit");

        labelAuthor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelAuthor.setForeground(new java.awt.Color(255, 255, 255));
        labelAuthor.setText("Pengarang");

        labelYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelYear.setForeground(new java.awt.Color(255, 255, 255));
        labelYear.setText("Tahun Terbit");

        labelCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCategory.setForeground(new java.awt.Color(255, 255, 255));
        labelCategory.setText("Kategori");

        labelQty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelQty.setForeground(new java.awt.Color(255, 255, 255));
        labelQty.setText("Jumlah Buku");

        jPanel2.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel2.setLayout(new java.awt.CardLayout());

        btnUpdate.setBackground(new java.awt.Color(87, 101, 116));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update Data");
        btnUpdate.setBorderPainted(false);
        btnUpdate.setPreferredSize(new java.awt.Dimension(100, 25));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, "card2");

        btnAdd.setBackground(new java.awt.Color(87, 101, 116));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Tambah Data");
        btnAdd.setBorderPainted(false);
        btnAdd.setPreferredSize(new java.awt.Dimension(100, 25));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelAuthor)
                            .addComponent(labelTitle)
                            .addComponent(labelPublisher)
                            .addComponent(labelYear)
                            .addComponent(labelCategory)
                            .addComponent(labelQty))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTitle)
                            .addComponent(comboPublisher, 0, 226, Short.MAX_VALUE)
                            .addComponent(txtQty)
                            .addComponent(txtAuthor)
                            .addComponent(txtYear)
                            .addComponent(comboCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitle))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPublisher))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAuthor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelYear))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCategory))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQty)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int iPublisher = comboPublisher.getSelectedIndex();
        int iCategory = comboCategory.getSelectedIndex();

        try {
            String sql = "INSERT INTO books (title, year, author, qty, category_id, publisher_id) "
                    + "VALUES('" + txtTitle.getText() + "','" + txtYear.getText() + "','" + txtAuthor.getText() + "','" + txtQty.getText() + "','" + arrCategoryId[iCategory] + "','" + arrPublisherId[iPublisher] + "')";
            System.out.println(sql);
            java.sql.Connection conn = (Connection) connection.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            dispose();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int iPublisher = comboPublisher.getSelectedIndex();
        int iCategory = comboCategory.getSelectedIndex();

        try {
            String sql = "UPDATE books SET title='" + txtTitle.getText() + "',year='" + txtYear.getText() + "',author='" + txtAuthor.getText() + "',qty='" + txtQty.getText() + "',category_id='" + arrCategoryId[iCategory] + "',publisher_id='" + arrPublisherId[iPublisher] + "'WHERE id='" + id + "'";
            java.sql.Connection conn = (Connection) connection.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            dispose();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed
    public String title, author;
    public int id, year, qty, categoryId, publisherId;
    public Integer[] arrPublisherId, arrCategoryId;

    public void setArrCategoryId(Integer[] array) {
        this.arrCategoryId = Arrays.copyOf(array, array.length);
    }

    public void setArrPublisherId(Integer[] array) {
        this.arrPublisherId = Arrays.copyOf(array, array.length);
    }

    public static int findIndex(Integer arr[], int t) {
        if (arr == null) {
            return -1;
        }

        int len = arr.length;
        int i = 0;

        while (i < len) {

            if (arr[i] == t) {
                return i;
            } else {
                i = i + 1;
            }
        }
        return -1;
    }

    public void viewData() {
        txtTitle.setText(title);
        txtYear.setText(Integer.toString(year));
        txtAuthor.setText(author);
        txtQty.setText(Integer.toString(qty));
        comboPublisher.setSelectedIndex(findIndex(arrPublisherId, publisherId));
        comboCategory.setSelectedIndex(findIndex(arrCategoryId, categoryId));
    }

    public void viewComboBox() {
        try {
            java.sql.Connection conn = (Connection) connection.configDB();
            java.sql.Statement stm = conn.createStatement();

            String sql = "SELECT * FROM publishers";
            java.sql.ResultSet res = stm.executeQuery(sql);
            Set<Integer> p = new HashSet<>();
            while (res.next()) {
                comboPublisher.addItem(res.getString("name"));
                p.add(res.getInt("id"));
            }
            int n = p.size();
            Integer pArr[] = new Integer[n];
            pArr = p.toArray(pArr);
            setArrPublisherId(pArr);

            sql = "SELECT * FROM categories";
            res = stm.executeQuery(sql);
            Set<Integer> c = new HashSet<>();
            while (res.next()) {
                comboCategory.addItem(res.getString("name"));
                c.add(res.getInt("id"));
            }
            n = c.size();
            Integer cArr[] = new Integer[n];
            cArr = c.toArray(cArr);
            setArrCategoryId(cArr);
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboCategory;
    private javax.swing.JComboBox<String> comboPublisher;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAuthor;
    private javax.swing.JLabel labelCategory;
    private javax.swing.JLabel labelPublisher;
    private javax.swing.JLabel labelQty;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelYear;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
